services:
    # Remove the public: true default once DI is implemented throughout the StepUp applications. See Pivotal #138225085
    _defaults:
        public: true

    surfnet_saml.saml.attribute_dictionary:
        class: Surfnet\SamlBundle\SAML2\Attribute\AttributeDictionary
        arguments:
            - null # Replaced in the Surfnet\SamlBundle\DependencyInjection\SurfnetSamlExtension based on configuration
        deprecated: ~
    Surfnet\SamlBundle\SAML2\Attribute\AttributeDictionary:
        alias: surfnet_saml.saml.attribute_dictionary

    surfnet_saml.configuration.metadata:
        class: Surfnet\SamlBundle\Metadata\MetadataConfiguration
        deprecated: ~
    Surfnet\SamlBundle\Metadata\MetadataConfiguration:
        alias: surfnet_saml.configuration.metadata

    surfnet_saml.configuration.hosted_entities:
        public: false
        class: Surfnet\SamlBundle\Entity\HostedEntities
        arguments:
            - '@router'
            - '@request_stack'
            - null # Replaced in the Surfnet\SamlBundle\DependencyInjection\SurfnetSamlExtension based on configuration
            - null # Replaced in the Surfnet\SamlBundle\DependencyInjection\SurfnetSamlExtension based on configuration
        deprecated: ~
    Surfnet\SamlBundle\Entity\HostedEntities:
        alias: surfnet_saml.configuration.hosted_entities
        public: false

    surfnet_saml.hosted.service_provider:
        class:   Surfnet\SamlBundle\Entity\ServiceProvider
        factory: ['@surfnet_saml.configuration.hosted_entities', getServiceProvider]
        deprecated: ~
    Surfnet\SamlBundle\Entity\ServiceProvider:
        alias: surfnet_saml.hosted.service_provider

    surfnet_saml.hosted.identity_provider:
        class:   Surfnet\SamlBundle\Entity\IdentityProvider
        factory: ['@surfnet_saml.configuration.hosted_entities', getIdentityProvider]
        deprecated: ~
    Surfnet\SamlBundle\Entity\IdentityProvider:
        alias: surfnet_saml.hosted.identity_provider

    surfnet_saml.http.binding_factory:
        class: Surfnet\SamlBundle\Http\HttpBindingFactory
        arguments:
            - '@surfnet_saml.http.redirect_binding'
            - '@surfnet_saml.http.post_binding'
        deprecated: ~
    Surfnet\SamlBundle\Http\HttpBindingFactory:
        alias: surfnet_saml.http.binding_factory

    surfnet_saml.http.redirect_binding:
        class: Surfnet\SamlBundle\Http\RedirectBinding
        arguments:
            - '@logger'
            - '@surfnet_saml.signing.signature_verifier'
            - '@?surfnet_saml.entity.entity_repository'
        deprecated: ~
    Surfnet\SamlBundle\Http\RedirectBinding:
        alias: surfnet_saml.http.redirect_binding

    surfnet_saml.http.post_binding:
        class: Surfnet\SamlBundle\Http\PostBinding
        arguments:
            - '@surfnet_saml.saml2.response_processor'
            - '@logger'
            - '@surfnet_saml.signing.signature_verifier'
            - '@?surfnet_saml.entity.entity_repository'
        deprecated: ~
    Surfnet\SamlBundle\Http\PostBinding:
        alias: surfnet_saml.http.post_binding

    surfnet_saml.metadata_factory:
        class: Surfnet\SamlBundle\Metadata\MetadataFactory
        arguments:
            - '@templating'
            - '@router'
            - '@surfnet_saml.signing_service'
            - '@surfnet_saml.configuration.metadata'
        deprecated: ~
    Surfnet\SamlBundle\Metadata\MetadataFactory:
        alias: surfnet_saml.metadata_factory

    surfnet_saml.signing_service:
        class: Surfnet\SamlBundle\Service\SigningService
        arguments:
            - '@surfnet_saml.saml2.keyloader'
            - '@surfnet_saml.saml2.privatekeyloader'
        deprecated: ~
    Surfnet\SamlBundle\Service\SigningService:
        alias: surfnet_saml.signing_service

    surfnet_saml.signing.signature_verifier:
        class: Surfnet\SamlBundle\Signing\SignatureVerifier
        arguments:
            - '@surfnet_saml.saml2.keyloader'
            - '@logger'
        deprecated: ~
    Surfnet\SamlBundle\Signing\SignatureVerifier:
        alias: surfnet_saml.signing.signature_verifier

    surfnet_saml.saml2.bridge_container:
        class: Surfnet\SamlBundle\SAML2\BridgeContainer
        arguments:
            - '@logger'
        deprecated: ~
    Surfnet\SamlBundle\SAML2\BridgeContainer:
        alias: surfnet_saml.saml2.bridge_container

    surfnet_saml.saml2.keyloader:
        public: false
        class: SAML2\Certificate\KeyLoader
        deprecated: ~
    SAML2\Certificate\KeyLoader:
        public: false
        alias: surfnet_saml.saml2.keyloader

    surfnet_saml.saml2.privatekeyloader:
        public: false
        class: SAML2\Certificate\PrivateKeyLoader
        deprecated: ~
    SAML2\Certificate\PrivateKeyLoader:
        public: false
        alias: surfnet_saml.saml2.privatekeyloader

    surfnet_saml.saml2.response_processor:
        public: false
        class: SAML2\Response\Processor
        arguments:
            - '@logger'
        deprecated: ~
    SAML2\Response\Processor:
        public: false
        alias: surfnet_saml.saml2.response_processor

    surfnet_saml.logger:
        class: Surfnet\SamlBundle\Monolog\SamlAuthenticationLogger
        arguments:
            - '@logger'
        deprecated: ~
    Surfnet\SamlBundle\Monolog\SamlAuthenticationLogger:
        alias: surfnet_saml.logger
