services:
    # Remove the public: true default once DI is implemented throughout the StepUp applications. See Pivotal #138225085
    _defaults:
        public: true

    surfnet_saml.saml.attribute_dictionary:
        class: Surfnet\SamlBundle\SAML2\Attribute\AttributeDictionary
        arguments:
            - null # Replaced in the Surfnet\SamlBundle\DependencyInjection\SurfnetSamlExtension based on configuration

    surfnet_saml.configuration.metadata:
        class: Surfnet\SamlBundle\Metadata\MetadataConfiguration

    surfnet_saml.configuration.hosted_entities:
        public: false
        class: Surfnet\SamlBundle\Entity\HostedEntities
        arguments:
            - '@router'
            - '@request_stack'
            - null # Replaced in the Surfnet\SamlBundle\DependencyInjection\SurfnetSamlExtension based on configuration
            - null # Replaced in the Surfnet\SamlBundle\DependencyInjection\SurfnetSamlExtension based on configuration

    surfnet_saml.hosted.service_provider:
        class:   Surfnet\SamlBundle\Entity\ServiceProvider
        factory: ['@surfnet_saml.configuration.hosted_entities', getServiceProvider]

    surfnet_saml.hosted.identity_provider:
        class:   Surfnet\SamlBundle\Entity\IdentityProvider
        factory: ['@surfnet_saml.configuration.hosted_entities', getIdentityProvider]

    surfnet_saml.http.binding_factory:
        class: Surfnet\SamlBundle\Http\HttpBindingFactory
        arguments:
            - '@surfnet_saml.http.redirect_binding'
            - '@surfnet_saml.http.post_binding'

    surfnet_saml.http.redirect_binding:
        class: Surfnet\SamlBundle\Http\RedirectBinding
        arguments:
            - '@logger'
            - '@surfnet_saml.signing.signature_verifier'
            - '@?surfnet_saml.entity.entity_repository'

    surfnet_saml.http.post_binding:
        class: Surfnet\SamlBundle\Http\PostBinding
        arguments:
            - '@surfnet_saml.saml2.response_processor'
            - '@logger'
            - '@surfnet_saml.signing.signature_verifier'
            - '@?surfnet_saml.entity.entity_repository'

    surfnet_saml.metadata_factory:
        class: Surfnet\SamlBundle\Metadata\MetadataFactory
        arguments:
            - '@templating'
            - '@router'
            - '@surfnet_saml.signing_service'
            - '@surfnet_saml.configuration.metadata'

    surfnet_saml.signing_service:
        class: Surfnet\SamlBundle\Service\SigningService
        arguments:
            - '@surfnet_saml.saml2.keyloader'
            - '@surfnet_saml.saml2.privatekeyloader'

    surfnet_saml.signing.signature_verifier:
        class: Surfnet\SamlBundle\Signing\SignatureVerifier
        arguments:
            - '@surfnet_saml.saml2.keyloader'
            - '@logger'

    surfnet_saml.saml2.bridge_container:
        class: Surfnet\SamlBundle\SAML2\BridgeContainer
        arguments:
            - '@logger'

    surfnet_saml.saml2.keyloader:
        public: false
        class: SAML2\Certificate\KeyLoader

    surfnet_saml.saml2.privatekeyloader:
        public: false
        class: SAML2\Certificate\PrivateKeyLoader

    surfnet_saml.saml2.response_processor:
        public: false
        class: SAML2\Response\Processor
        arguments:
            - '@logger'

    surfnet_saml.logger:
        class: Surfnet\SamlBundle\Monolog\SamlAuthenticationLogger
        arguments:
            - '@logger'
